name: Build and Release
on: workflow_dispatch
jobs:
  pyinstaller-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'src/logalert.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'logalert'
          options: --onefile, --name "logalert"
